In [15]:
import pandas as pd
import numpy as np

In [23]:
features = ['Elevation', 'Aspect', 'Slope', 'Horizontal_Dist_To_Water', 
 'Vertical_Dist_To_Water', 'Horizontal_Dist_To_Roadways', 'Hillshade_9am'
'Hillshade_noon', 'Hillshade_3pm', 'Horizontal_Dist_To_Fire_Points',
 'WA_Rawah', 'Wa_Neota', 'WA_Comanche', 'WA_CacheLaPoudre']
for i in range(13, 54):
    features.append('Soiltype' + str(i))
features.append('Cover_Type')

df = pd.read_csv('covtype.data', header=None, names=features)

In [24]:
df.head()

,Elevation,Aspect,Slope,Horizontal_Dist_To_Water,Vertical_Dist_To_Water,Horizontal_Dist_To_Roadways,Hillshade_9amHillshade_noon,Hillshade_3pm,Horizontal_Dist_To_Fire_Points,WA_Rawah,...,Soiltype45,Soiltype46,Soiltype47,Soiltype48,Soiltype49,Soiltype50,Soiltype51,Soiltype52,Soiltype53,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5